[package]
name = "advent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bimap = "0.6"
counter = "0.5"
itertools = "0.10"
pest = "2.0"
pest_derive = "2.0"
regex = "1"
thiserror = "1"
